# Layouts
enabled_layouts Splits, Stack

# Split shortcuts (maintain working directory)
map ctrl+shift+Enter launch --location=split  --cwd=current
map ctrl+shift+5 launch --location=vsplit --cwd=current
map ctrl+shift+' launch --location=hsplit --cwd=current

