# Layouts
enabled_layouts Splits, Stack

# Split shortcuts (maintain working directory)
map ctrl+shift+Enter launch --location=split  --cwd=current
map ctrl+shift+Equal launch --location=vsplit --cwd=current
map ctrl+shift+Minus launch --location=hsplit --cwd=current

